<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Auto-generated by EAM-MES Package — eam:sync-extensions
 * Extensions  : App\Extensions\EquipmentExtension
 * Generated at: 2026-07-15 01:15:20
 *
 * DO NOT EDIT MANUALLY.
 * Re-run `php artisan eam:sync-extensions` to regenerate.
 */
return new class extends Migration {
    public function up(): void
    {
        Schema::table('eamo_equipment', function (Blueprint $table) {
            $table->string('parent_id', 36)->nullable()->after('id');
            $table->foreign('parent_id')
                ->references('id')
                ->on('eamo_equipment')
                ->restrictOnDelete()
                ->cascadeOnUpdate();
        });
    }

    public function down(): void
    {
        Schema::table('eamo_equipment', function (Blueprint $table) {
            $table->dropForeign(['parent_id']);
            $table->dropColumn('parent_id');
        });
    }
};
